{
  "uid" : "5e4d1b792a3fc697",
  "name" : "User can't successfully log in with invalid username.",
  "fullName" : "tests.core_features.test_login.TestLogin#test_login_with_invalid_username",
  "historyId" : "d9da1d35f9d1a309fb04ddfe89a222bc",
  "time" : {
    "start" : 1704756570957,
    "stop" : 1704756572424,
    "duration" : 1467
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
  "statusTrace" : "tests/core_features/test_login.py:69: in test_login_with_invalid_username\n    login_page.error_text.assert_error(\"The username and password could not be verified.\")\n        driver     = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"898f8c1b211b8912e23895f63d00993f\")>\n        home_page  = <src.pages.home_page.HomePage object at 0x7f4f58d28810>\n        login_page = <src.pages.login_page.LoginPage object at 0x7f4f58d28710>\n        self       = <test_login.TestLogin object at 0x7f4f5a4cb210>\nsrc/base/base_element.py:70: in assert_error\n    pytest.xfail(reason=\"Known server-side issue\")\nE   _pytest.outcomes.XFailed: Known server-side issue\n        current_error = 'An internal error has occurred and has been logged.'\n        expected_error = 'The username and password could not be verified.'\n        self       = <src.base.base_element.BaseElement object at 0x7f4f57358a50>\n        server_error = 'An internal error has occurred and has been logged.'",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "Initialize driver",
    "time" : {
      "start" : 1704756570110,
      "stop" : 1704756570957,
      "duration" : 847
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "Health check request",
    "time" : {
      "start" : 1704756489914,
      "stop" : 1704756490512,
      "duration" : 598
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1704756489894,
      "stop" : 1704756489914,
      "duration" : 20
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "testStage" : {
    "status" : "skipped",
    "statusMessage" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
    "statusTrace" : "tests/core_features/test_login.py:69: in test_login_with_invalid_username\n    login_page.error_text.assert_error(\"The username and password could not be verified.\")\n        driver     = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"898f8c1b211b8912e23895f63d00993f\")>\n        home_page  = <src.pages.home_page.HomePage object at 0x7f4f58d28810>\n        login_page = <src.pages.login_page.LoginPage object at 0x7f4f58d28710>\n        self       = <test_login.TestLogin object at 0x7f4f5a4cb210>\nsrc/base/base_element.py:70: in assert_error\n    pytest.xfail(reason=\"Known server-side issue\")\nE   _pytest.outcomes.XFailed: Known server-side issue\n        current_error = 'An internal error has occurred and has been logged.'\n        expected_error = 'The username and password could not be verified.'\n        self       = <src.base.base_element.BaseElement object at 0x7f4f57358a50>\n        server_error = 'An internal error has occurred and has been logged.'",
    "steps" : [ {
      "name" : "Navigate to Home page",
      "time" : {
        "start" : 1704756570957,
        "stop" : 1704756571664,
        "duration" : 707
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    }, {
      "name" : "Fill in valid password, but invalid username",
      "time" : {
        "start" : 1704756571664,
        "stop" : 1704756571829,
        "duration" : 165
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    }, {
      "name" : "Log in",
      "time" : {
        "start" : 1704756571829,
        "stop" : 1704756572325,
        "duration" : 496
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    }, {
      "name" : "Check error message is displayed",
      "time" : {
        "start" : 1704756572325,
        "stop" : 1704756572424,
        "duration" : 99
      },
      "status" : "failed",
      "statusMessage" : "_pytest.outcomes.XFailed: Known server-side issue\n",
      "statusTrace" : "  File \"/usr/workspace/tests/core_features/test_login.py\", line 69, in test_login_with_invalid_username\n    login_page.error_text.assert_error(\"The username and password could not be verified.\")\n  File \"/usr/workspace/src/base/base_element.py\", line 70, in assert_error\n    pytest.xfail(reason=\"Known server-side issue\")\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/outcomes.py\", line 256, in xfail\n    raise XFailed(reason)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "stepsCount" : 0,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "stepsCount" : 4,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "Initialize driver::0",
    "time" : {
      "start" : 1704756572428,
      "stop" : 1704756572487,
      "duration" : 59
    },
    "status" : "passed",
    "steps" : [ {
      "name" : "Terminate driver",
      "time" : {
        "start" : 1704756572428,
        "stop" : 1704756572487,
        "duration" : 59
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 1,
    "hasContent" : true
  } ],
  "labels" : [ {
    "name" : "severity",
    "value" : "Minor"
  }, {
    "name" : "feature",
    "value" : "PARA-15261: User login"
  }, {
    "name" : "epic",
    "value" : "PARA-15240: User registration and authentication"
  }, {
    "name" : "parentSuite",
    "value" : "tests.core_features"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "4adcfedac879"
  }, {
    "name" : "thread",
    "value" : "1-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.core_features.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "minor",
    "retries" : [ ],
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "5e4d1b792a3fc697.json",
  "parameterValues" : [ ]
}