{
  "uid" : "626f0d73e976d6c2",
  "name" : "User can't successfully log in with invalid username.",
  "fullName" : "tests.core_features.test_login.TestLogin#test_login_with_invalid_username",
  "historyId" : "d9da1d35f9d1a309fb04ddfe89a222bc",
  "time" : {
    "start" : 1704839546391,
    "stop" : 1704839547678,
    "duration" : 1287
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
  "statusTrace" : "tests/core_features/test_login.py:69: in test_login_with_invalid_username\n    login_page.error_text.assert_error(\"The username and password could not be verified.\")\n        driver     = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"6614466319b67cd17fd6ae92df2ab20a\")>\n        home_page  = <src.pages.home_page.HomePage object at 0x7f8db9af9890>\n        login_page = <src.pages.login_page.LoginPage object at 0x7f8db9afb890>\n        self       = <test_login.TestLogin object at 0x7f8dbcc87a10>\nsrc/base/base_element.py:71: in assert_error\n    pytest.xfail(reason=\"Known server-side issue\")\nE   _pytest.outcomes.XFailed: Known server-side issue\n        current_error = 'An internal error has occurred and has been logged.'\n        expected_error = 'The username and password could not be verified.'\n        self       = <src.base.base_element.BaseElement object at 0x7f8db9af8f90>\n        server_error = 'An internal error has occurred and has been logged.'",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "Health check request",
    "time" : {
      "start" : 1704839460802,
      "stop" : 1704839461263,
      "duration" : 461
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "Initialize driver",
    "time" : {
      "start" : 1704839545553,
      "stop" : 1704839546391,
      "duration" : 838
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1704839460781,
      "stop" : 1704839460801,
      "duration" : 20
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "testStage" : {
    "status" : "skipped",
    "statusMessage" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
    "statusTrace" : "tests/core_features/test_login.py:69: in test_login_with_invalid_username\n    login_page.error_text.assert_error(\"The username and password could not be verified.\")\n        driver     = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"6614466319b67cd17fd6ae92df2ab20a\")>\n        home_page  = <src.pages.home_page.HomePage object at 0x7f8db9af9890>\n        login_page = <src.pages.login_page.LoginPage object at 0x7f8db9afb890>\n        self       = <test_login.TestLogin object at 0x7f8dbcc87a10>\nsrc/base/base_element.py:71: in assert_error\n    pytest.xfail(reason=\"Known server-side issue\")\nE   _pytest.outcomes.XFailed: Known server-side issue\n        current_error = 'An internal error has occurred and has been logged.'\n        expected_error = 'The username and password could not be verified.'\n        self       = <src.base.base_element.BaseElement object at 0x7f8db9af8f90>\n        server_error = 'An internal error has occurred and has been logged.'",
    "steps" : [ {
      "name" : "Navigate to Home page",
      "time" : {
        "start" : 1704839546392,
        "stop" : 1704839546978,
        "duration" : 586
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    }, {
      "name" : "Fill in valid password, but invalid username",
      "time" : {
        "start" : 1704839546979,
        "stop" : 1704839547136,
        "duration" : 157
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    }, {
      "name" : "Log in",
      "time" : {
        "start" : 1704839547136,
        "stop" : 1704839547576,
        "duration" : 440
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    }, {
      "name" : "Check error message is displayed",
      "time" : {
        "start" : 1704839547576,
        "stop" : 1704839547678,
        "duration" : 102
      },
      "status" : "failed",
      "statusMessage" : "_pytest.outcomes.XFailed: Known server-side issue\n",
      "statusTrace" : "  File \"/usr/workspace/tests/core_features/test_login.py\", line 69, in test_login_with_invalid_username\n    login_page.error_text.assert_error(\"The username and password could not be verified.\")\n  File \"/usr/workspace/src/base/base_element.py\", line 71, in assert_error\n    pytest.xfail(reason=\"Known server-side issue\")\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/outcomes.py\", line 256, in xfail\n    raise XFailed(reason)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "stepsCount" : 0,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "stepsCount" : 4,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "Initialize driver::0",
    "time" : {
      "start" : 1704839547682,
      "stop" : 1704839547738,
      "duration" : 56
    },
    "status" : "passed",
    "steps" : [ {
      "name" : "Terminate driver",
      "time" : {
        "start" : 1704839547682,
        "stop" : 1704839547738,
        "duration" : 56
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 1,
    "hasContent" : true
  } ],
  "labels" : [ {
    "name" : "feature",
    "value" : "PARA-15261: User login"
  }, {
    "name" : "severity",
    "value" : "Minor"
  }, {
    "name" : "epic",
    "value" : "PARA-15240: User registration and authentication"
  }, {
    "name" : "parentSuite",
    "value" : "tests.core_features"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "3d908ae8aa0b"
  }, {
    "name" : "thread",
    "value" : "1-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.core_features.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "minor",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 0,
        "skipped" : 4,
        "passed" : 0,
        "unknown" : 0,
        "total" : 4
      },
      "items" : [ {
        "uid" : "8b2995c1d1a4e4b5",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704789360100,
          "stop" : 1704789361271,
          "duration" : 1171
        }
      }, {
        "uid" : "e0e21325e73abf2c",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704759030280,
          "stop" : 1704759031332,
          "duration" : 1052
        }
      }, {
        "uid" : "5e4d1b792a3fc697",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704756570957,
          "stop" : 1704756572424,
          "duration" : 1467
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "626f0d73e976d6c2.json",
  "parameterValues" : [ ]
}