{
  "uid" : "edba5e4295264388",
  "name" : "Newly created account is displayed in the table",
  "fullName" : "tests.core_features.test_account_display.TestAccountDisplay#test_new_account_display",
  "historyId" : "63bec0651d7837f23a81ac9022330693",
  "time" : {
    "start" : 1704908682681,
    "stop" : 1704908682681,
    "duration" : 0
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL reason: Health check failed with status code 502\n\n_pytest.outcomes.XFailed: Health check failed with status code 502",
  "statusTrace" : "conftest.py:32: in health_check\n    pytest.xfail(reason=f\"Health check failed with status code {response.status_code}\")\nE   _pytest.outcomes.XFailed: Health check failed with status code 502\n        response   = <Response [502]>\n        url        = 'https://parabank.parasoft.com/parabank'",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "Health check request",
    "time" : {
      "start" : 1704908682351,
      "stop" : 1704908682639,
      "duration" : 288
    },
    "status" : "failed",
    "statusMessage" : "_pytest.outcomes.XFailed: Health check failed with status code 502\n",
    "statusTrace" : "  File \"/usr/local/lib/python3.11/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/workspace/conftest.py\", line 32, in health_check\n    pytest.xfail(reason=f\"Health check failed with status code {response.status_code}\")\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/outcomes.py\", line 256, in xfail\n    raise XFailed(reason)\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "stepsCount" : 0,
    "hasContent" : true
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1704908682330,
      "stop" : 1704908682350,
      "duration" : 20
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "PARA-15251: Account display in Accounts Overview table"
  }, {
    "name" : "severity",
    "value" : "Critical"
  }, {
    "name" : "epic",
    "value" : "PARA-15241: Account operations"
  }, {
    "name" : "parentSuite",
    "value" : "tests.core_features"
  }, {
    "name" : "suite",
    "value" : "test_account_display"
  }, {
    "name" : "subSuite",
    "value" : "TestAccountDisplay"
  }, {
    "name" : "host",
    "value" : "457bd63967c0"
  }, {
    "name" : "thread",
    "value" : "1-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.core_features.test_account_display"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "critical",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 1,
        "skipped" : 1,
        "passed" : 4,
        "unknown" : 0,
        "total" : 6
      },
      "items" : [ {
        "uid" : "4702b8bb7a12d4ce",
        "status" : "passed",
        "time" : {
          "start" : 1704874910534,
          "stop" : 1704874914279,
          "duration" : 3745
        }
      }, {
        "uid" : "71069ba692ccd2f7",
        "status" : "passed",
        "time" : {
          "start" : 1704839473835,
          "stop" : 1704839477952,
          "duration" : 4117
        }
      }, {
        "uid" : "fd71f686a0e79e30",
        "status" : "passed",
        "time" : {
          "start" : 1704789282221,
          "stop" : 1704789285426,
          "duration" : 3205
        }
      }, {
        "uid" : "49cf0e1ba9e3a695",
        "status" : "passed",
        "time" : {
          "start" : 1704758981286,
          "stop" : 1704758984580,
          "duration" : 3294
        }
      }, {
        "uid" : "d863d1a8a935cf1f",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found\n  (Session info: headless chrome=119.0.6045.159); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception",
        "time" : {
          "start" : 1704756515781,
          "stop" : 1704756518138,
          "duration" : 2357
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "edba5e4295264388.json",
  "parameterValues" : [ ]
}