{
  "uid" : "f83d04c6b769b97a",
  "name" : "User can't successfully log in with invalid password.",
  "fullName" : "tests.core_features.test_login.TestLogin#test_login_with_invalid_password",
  "historyId" : "0ca18d8bd97e96e2fad3ec13e04117a8",
  "time" : {
    "start" : 1705392752889,
    "stop" : 1705392754079,
    "duration" : 1190
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
  "statusTrace" : "tests/core_features/test_login.py:50: in test_login_with_invalid_password\n    login_page.error_text.assert_error(\"The username and password could not be verified.\")\n        driver     = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"9a243af42eb5ead8a64b917a7bec8e05\")>\n        home_page  = <src.pages.home_page.HomePage object at 0x7f1cb9d86cd0>\n        login_page = <src.pages.login_page.LoginPage object at 0x7f1cbced6510>\n        self       = <test_login.TestLogin object at 0x7f1cbcee0a10>\nsrc/base/base_element.py:71: in assert_error\n    pytest.xfail(reason=\"Known server-side issue\")\nE   _pytest.outcomes.XFailed: Known server-side issue\n        current_error = 'An internal error has occurred and has been logged.'\n        expected_error = 'The username and password could not be verified.'\n        self       = <src.base.base_element.BaseElement object at 0x7f1cbce6df50>\n        server_error = 'An internal error has occurred and has been logged.'",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "Health check request",
    "time" : {
      "start" : 1705392682937,
      "stop" : 1705392683648,
      "duration" : 711
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "Initialize driver",
    "time" : {
      "start" : 1705392752054,
      "stop" : 1705392752889,
      "duration" : 835
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1705392682916,
      "stop" : 1705392682937,
      "duration" : 21
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "testStage" : {
    "status" : "skipped",
    "statusMessage" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
    "statusTrace" : "tests/core_features/test_login.py:50: in test_login_with_invalid_password\n    login_page.error_text.assert_error(\"The username and password could not be verified.\")\n        driver     = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"9a243af42eb5ead8a64b917a7bec8e05\")>\n        home_page  = <src.pages.home_page.HomePage object at 0x7f1cb9d86cd0>\n        login_page = <src.pages.login_page.LoginPage object at 0x7f1cbced6510>\n        self       = <test_login.TestLogin object at 0x7f1cbcee0a10>\nsrc/base/base_element.py:71: in assert_error\n    pytest.xfail(reason=\"Known server-side issue\")\nE   _pytest.outcomes.XFailed: Known server-side issue\n        current_error = 'An internal error has occurred and has been logged.'\n        expected_error = 'The username and password could not be verified.'\n        self       = <src.base.base_element.BaseElement object at 0x7f1cbce6df50>\n        server_error = 'An internal error has occurred and has been logged.'",
    "steps" : [ {
      "name" : "Navigate to Home page",
      "time" : {
        "start" : 1705392752889,
        "stop" : 1705392753529,
        "duration" : 640
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    }, {
      "name" : "Fill in valid username, but invalid password",
      "time" : {
        "start" : 1705392753529,
        "stop" : 1705392753685,
        "duration" : 156
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    }, {
      "name" : "Log in",
      "time" : {
        "start" : 1705392753685,
        "stop" : 1705392753991,
        "duration" : 306
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    }, {
      "name" : "Check error message is displayed",
      "time" : {
        "start" : 1705392753991,
        "stop" : 1705392754078,
        "duration" : 87
      },
      "status" : "failed",
      "statusMessage" : "_pytest.outcomes.XFailed: Known server-side issue\n",
      "statusTrace" : "  File \"/usr/workspace/tests/core_features/test_login.py\", line 50, in test_login_with_invalid_password\n    login_page.error_text.assert_error(\"The username and password could not be verified.\")\n  File \"/usr/workspace/src/base/base_element.py\", line 71, in assert_error\n    pytest.xfail(reason=\"Known server-side issue\")\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/outcomes.py\", line 256, in xfail\n    raise XFailed(reason)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "stepsCount" : 0,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "stepsCount" : 4,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "Initialize driver::0",
    "time" : {
      "start" : 1705392754117,
      "stop" : 1705392754173,
      "duration" : 56
    },
    "status" : "passed",
    "steps" : [ {
      "name" : "Terminate driver",
      "time" : {
        "start" : 1705392754117,
        "stop" : 1705392754173,
        "duration" : 56
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 1,
    "hasContent" : true
  } ],
  "labels" : [ {
    "name" : "feature",
    "value" : "PARA-15261: User login"
  }, {
    "name" : "epic",
    "value" : "PARA-15240: User registration and authentication"
  }, {
    "name" : "severity",
    "value" : "Minor"
  }, {
    "name" : "parentSuite",
    "value" : "tests.core_features"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "12837cb7fc97"
  }, {
    "name" : "thread",
    "value" : "1-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.core_features.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "minor",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 1,
        "skipped" : 8,
        "passed" : 1,
        "unknown" : 0,
        "total" : 10
      },
      "items" : [ {
        "uid" : "5e7dcbff4cf558ab",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
        "time" : {
          "start" : 1705147649692,
          "stop" : 1705147666962,
          "duration" : 17270
        }
      }, {
        "uid" : "e190f26f7214f7d0",
        "status" : "passed",
        "time" : {
          "start" : 1705016480476,
          "stop" : 1705016481711,
          "duration" : 1235
        }
      }, {
        "uid" : "e04b62efc34bb97d",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704913007085,
          "stop" : 1704913007821,
          "duration" : 736
        }
      }, {
        "uid" : "34036144644cbdca",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Health check failed with status code 502\n\n_pytest.outcomes.XFailed: Health check failed with status code 502",
        "time" : {
          "start" : 1704908682724,
          "stop" : 1704908682724,
          "duration" : 0
        }
      }, {
        "uid" : "bf6294b63c28caed",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704874970180,
          "stop" : 1704874971491,
          "duration" : 1311
        }
      }, {
        "uid" : "d87ec95d2bd7a1d7",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704839544422,
          "stop" : 1704839545491,
          "duration" : 1069
        }
      }, {
        "uid" : "ceab7a397b75762c",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704789358098,
          "stop" : 1704789359199,
          "duration" : 1101
        }
      }, {
        "uid" : "bb142fe10b5e53ec",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704759028518,
          "stop" : 1704759029330,
          "duration" : 812
        }
      }, {
        "uid" : "cce9cde06874d2bf",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704756568705,
          "stop" : 1704756570047,
          "duration" : 1342
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "f83d04c6b769b97a.json",
  "parameterValues" : [ ]
}